services:
  app:
    image: oven/bun:latest
    container_name: omnidump
    user: bun
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: omnidump_db
    environment:
      - POSTGRES_DB=omnidump
      - POSTGRES_USER=omnidump_user
      - POSTGRES_PASSWORD=omnidump_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: omnidump_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: