/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestConnectionRouteImport } from './routes/api/test-connection'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as ApiExportSchemaRouteImport } from './routes/api/export-schema'
import { Route as ApiExportCsvRouteImport } from './routes/api/export-csv'
import { Route as ApiDumpRouteImport } from './routes/api/dump'
import { Route as ApiDownloadRejectRouteImport } from './routes/api/download-reject'
import { Route as ApiDownloadDumpRouteImport } from './routes/api/download-dump'

const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestConnectionRoute = ApiTestConnectionRouteImport.update({
  id: '/api/test-connection',
  path: '/api/test-connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportSchemaRoute = ApiExportSchemaRouteImport.update({
  id: '/api/export-schema',
  path: '/api/export-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportCsvRoute = ApiExportCsvRouteImport.update({
  id: '/api/export-csv',
  path: '/api/export-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDumpRoute = ApiDumpRouteImport.update({
  id: '/api/dump',
  path: '/api/dump',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRejectRoute = ApiDownloadRejectRouteImport.update({
  id: '/api/download-reject',
  path: '/api/download-reject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadDumpRoute = ApiDownloadDumpRouteImport.update({
  id: '/api/download-dump',
  path: '/api/download-dump',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schema': typeof SchemaRoute
  '/api/download-dump': typeof ApiDownloadDumpRoute
  '/api/download-reject': typeof ApiDownloadRejectRoute
  '/api/dump': typeof ApiDumpRoute
  '/api/export-csv': typeof ApiExportCsvRoute
  '/api/export-schema': typeof ApiExportSchemaRoute
  '/api/import': typeof ApiImportRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schema': typeof SchemaRoute
  '/api/download-dump': typeof ApiDownloadDumpRoute
  '/api/download-reject': typeof ApiDownloadRejectRoute
  '/api/dump': typeof ApiDumpRoute
  '/api/export-csv': typeof ApiExportCsvRoute
  '/api/export-schema': typeof ApiExportSchemaRoute
  '/api/import': typeof ApiImportRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schema': typeof SchemaRoute
  '/api/download-dump': typeof ApiDownloadDumpRoute
  '/api/download-reject': typeof ApiDownloadRejectRoute
  '/api/dump': typeof ApiDumpRoute
  '/api/export-csv': typeof ApiExportCsvRoute
  '/api/export-schema': typeof ApiExportSchemaRoute
  '/api/import': typeof ApiImportRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/test-connection': typeof ApiTestConnectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/schema'
    | '/api/download-dump'
    | '/api/download-reject'
    | '/api/dump'
    | '/api/export-csv'
    | '/api/export-schema'
    | '/api/import'
    | '/api/seed'
    | '/api/test-connection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/schema'
    | '/api/download-dump'
    | '/api/download-reject'
    | '/api/dump'
    | '/api/export-csv'
    | '/api/export-schema'
    | '/api/import'
    | '/api/seed'
    | '/api/test-connection'
  id:
    | '__root__'
    | '/'
    | '/schema'
    | '/api/download-dump'
    | '/api/download-reject'
    | '/api/dump'
    | '/api/export-csv'
    | '/api/export-schema'
    | '/api/import'
    | '/api/seed'
    | '/api/test-connection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchemaRoute: typeof SchemaRoute
  ApiDownloadDumpRoute: typeof ApiDownloadDumpRoute
  ApiDownloadRejectRoute: typeof ApiDownloadRejectRoute
  ApiDumpRoute: typeof ApiDumpRoute
  ApiExportCsvRoute: typeof ApiExportCsvRoute
  ApiExportSchemaRoute: typeof ApiExportSchemaRoute
  ApiImportRoute: typeof ApiImportRoute
  ApiSeedRoute: typeof ApiSeedRoute
  ApiTestConnectionRoute: typeof ApiTestConnectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-connection': {
      id: '/api/test-connection'
      path: '/api/test-connection'
      fullPath: '/api/test-connection'
      preLoaderRoute: typeof ApiTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-schema': {
      id: '/api/export-schema'
      path: '/api/export-schema'
      fullPath: '/api/export-schema'
      preLoaderRoute: typeof ApiExportSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export-csv': {
      id: '/api/export-csv'
      path: '/api/export-csv'
      fullPath: '/api/export-csv'
      preLoaderRoute: typeof ApiExportCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dump': {
      id: '/api/dump'
      path: '/api/dump'
      fullPath: '/api/dump'
      preLoaderRoute: typeof ApiDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-reject': {
      id: '/api/download-reject'
      path: '/api/download-reject'
      fullPath: '/api/download-reject'
      preLoaderRoute: typeof ApiDownloadRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download-dump': {
      id: '/api/download-dump'
      path: '/api/download-dump'
      fullPath: '/api/download-dump'
      preLoaderRoute: typeof ApiDownloadDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchemaRoute: SchemaRoute,
  ApiDownloadDumpRoute: ApiDownloadDumpRoute,
  ApiDownloadRejectRoute: ApiDownloadRejectRoute,
  ApiDumpRoute: ApiDumpRoute,
  ApiExportCsvRoute: ApiExportCsvRoute,
  ApiExportSchemaRoute: ApiExportSchemaRoute,
  ApiImportRoute: ApiImportRoute,
  ApiSeedRoute: ApiSeedRoute,
  ApiTestConnectionRoute: ApiTestConnectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
